<<<<<<< Updated upstream
theme: jekyll-theme-cayman
title: BlendMimic3D 
show_downloads: true
description: A synthetic dataset developed using Blender, designed to enhance Human Pose Estimation (HPE) research. 

