theme: jekyll-theme-cayman
title: BlendMimic3D 
show_downloads: true
google_analytics:
description: A synthetic dataset developed using Blender, designed to enhance Human Pose Estimation (HPE) research. 

